EPISODE_NAMES = {
    1: "The Boy in the Iceberg",
    2: "The Avatar Returns",
    3: "The Southern Air Temple",
    4: "The Warriors of Kyoshi",
    5: "The King of Omashu",
    6: "Imprisoned",
    7: "The Spirit World (Winter Solstice, Part 1)",
    8: "Avatar Roku (Winter Solstice, Part 2)",
    9: "The Waterbending Scroll",
    10: "Jet",
    11: "The Great Divide",
    12: "The Storm",
    13: "The Blue Spirit",
    14: "The Fortuneteller",
    15: "Bato of the Water Tribe",
    16: "The Deserter",
    17: "The Northern Air Temple",
    18: "The Waterbending Master",
    19: "The Siege of the North, Part 1",
    20: "The Siege of the North, Part 2",
    21: "The Avatar State",
    22: "The Cave of Two Lovers",
    23: "Return to Omashu",
    24: "The Swamp",
    25: "Avatar Day",
    26: "The Blind Bandit",
    27: "Zuko Alone",
    28: "The Chase",
    29: "Bitter Work",
    30: "The Library",
    31: "The Desert",
    32: "The Serpent's Pass",
    33: "The Drill",
    34: "City of Walls and Secrets",
    35: "The Tales of Ba Sing Se",
    36: "Appa's Lost Days",
    37: "Lake Laogai",
    38: "The Earth King",
    39: "The Guru",
    40: "The Crossroads of Destiny",
    41: "The Awakening",
    42: "The Headband",
    43: "The Painted Lady",
    44: "Sokka's Master",
    45: "The Beach",
    46: "The Avatar and the Fire Lord",
    47: "The Runaway",
    48: "The Puppetmaster",
    49: "Nightmares and Daydreams",
    50: "The Day of Black Sun, Part 1: The Invasion",
    51: "The Day of Black Sun, Part 2: The Eclipse",
    52: "The Western Air Temple",
    53: "The Firebending Masters",
    54: "The Boiling Rock, Part 1",
    55: "The Boiling Rock, Part 2",
    56: "The Southern Raiders",
    57: "The Ember Island Players",
    58: "Sozin's Comet, Part 1: The Phoenix King",
    59: "Sozin's Comet, Part 2: The Old Masters",
    60: "Sozin's Comet, Part 3: Into the Inferno",
    61: "Sozin's Comet, Part 4: Avatar Aang",
}